repos:
  - repo: local
    hooks:
      - id: isort
        name: Sorting imports
        description: Sort all python import statements.
        entry: isort .
        language: python
        types: [python]
      - id: black
        name: Format code
        description: Formal all python code using black.
        entry: black -q .
        language: python
        types: [python]
      - id: flake8
        name: Check linting
        description: Lint the code using flake9
        entry: flake8
        language: python
        types: [python]
