# This is a basic workflow to help you get started with Actions

name: Publish to PYPI

# Controls when the workflow will run
on:
  push:
    branches:
      - "!*"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified

      # Install package and pytest
      - name: Install
        run: pip install .[dev]

      # Run pytest
      - name: Run tests
        run: pytest

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified

      - name: Install build dependencies
        run: pip install --upgrade build twine

      - name: Run build
        run: python -m build

      - name: Upload artifacts
        env: # Or as an environment variable
          API_TOKEN: ${{ secrets.pypi_api_token }}
        run: python -m twine upload -u __token__ -p "$API_TOKEN" dist/*
